github.com:
    users:
        TeSN6868:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: TeSN6868
